### ISSUE TITLE
Inked Filter Accordion required Inked Accordion

### ISSUE THREAD

**Issue by afwd** [wpinked/widgets-for-siteorigin#2]
Inked Filter Accordion will only work if Inked Accordion is also activated, otherwise the required accordian.js file is not available

**Comment by adiraomj** [comment]
Thanks for pointing it. I hadn't realised it would work that way.

I will sort it out.

**Comment by adiraomj** [comment]
Fixed in commit 9f63c0f20477680f095473c79c3c1b91208a668a
