### ISSUE TITLE
Visibility: Display Pixel Amount (width) for screen sizes

### ISSUE THREAD

**Issue by AlexGStapleton** [wpinked/widgets-for-siteorigin#23]
To clear up potential confusion it would be a good idea to reference the pixel width of the screen size. 

For example, Small (320px) is much clearer than just labelling it as just small.

**Comment by adiraomj** [comment]
Great suggestion. Will implement it in the next update.

**Comment by adiraomj** [comment]
Implemented in 85eb75a60d8a69f11657cab0666cfc24f1c40dbc
