### ISSUE TITLE
Tabs: Allow linking to certain tabs

### ISSUE THREAD

**Issue by AlexGStapleton** [wpinked/widgets-for-siteorigin#24]
[Reference thread](https://siteorigin.com/thread/tabs-and-ancores/)

You should be able to link directly to a tab by using typical methods.
For example, if I link to example.com/#tab-c it should open tab c on load.

**Comment by adiraomj** [comment]
@AlexGStapleton deep linking is something I plan to add to accordions and tabs. Thanks for the help.

**Comment by adiraomj** [comment]
Implemented in a3080519b4cfbb2aa272d35805dcc7c0c500907e
