### ISSUE TITLE
Inked Filter Accordion id must be specified

### ISSUE THREAD

**Issue by afwd** [wpinked/widgets-for-siteorigin#3]
Failing to specify an id to when creating an accordion results in id for each items being -1, -2, -3 etc.

This breaks the functionality of the accordion.

ID should be a required field, or auto generated

**Comment by adiraomj** [comment]
Thank you for the useful feedback.

I will start working on this. I will also apply the changes to the tabs widget.

**Comment by adiraomj** [comment]
Fixed in commit 62392299900f6ef346c5b226d3dac8a38028b7d5
